// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Jun2020.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IgracMec", b =>
                {
                    b.Property<int>("IgraciID")
                        .HasColumnType("int");

                    b.Property<int>("MeceviID")
                        .HasColumnType("int");

                    b.HasKey("IgraciID", "MeceviID");

                    b.HasIndex("MeceviID");

                    b.ToTable("IgracMec");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ATPRang")
                        .HasColumnType("int");

                    b.Property<int>("Godine")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoeniS1I1")
                        .HasColumnType("int");

                    b.Property<int>("PoeniS1I2")
                        .HasColumnType("int");

                    b.Property<int>("PoeniS2I1")
                        .HasColumnType("int");

                    b.Property<int>("PoeniS2I2")
                        .HasColumnType("int");

                    b.Property<int>("Setovi1")
                        .HasColumnType("int");

                    b.Property<int>("Setovi2")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("IgracMec", b =>
                {
                    b.HasOne("Models.Igrac", null)
                        .WithMany()
                        .HasForeignKey("IgraciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Mec", null)
                        .WithMany()
                        .HasForeignKey("MeceviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
